export const CHANGE_TODO_ITEM = 'change_todo_item'
export const ADD_TODO_ITEM = 'add_todo_item'
export const DELETE_TODO_ITEM = 'delete_todo_item'
export const INIT_LIST_ACTION = 'init_list_action'
export const GETINITLIST = 'get_init_list'